# Base labels
DNS:
  - dns/**

repo:
  - .github/**
  - ./*

# Specific domains
"Domain: robroyart.xyz":
  - dns/domains/robroyart.xyz.js

"Domain: polishkendamacommunity.pl":
  - dns/domains/polishkendamacommunity.pl.js
