# Base labels
DNS:
  - dns/**

repo:
  - .github/**
  - ./*

# Specific domains
domain/robroyart.xyz:
  - dns/domains/robroyart.xyz.js

domain/polishkendamacommunity.pl:
  - dns/domains/polishkendamacommunity.pl.js

domain/f4dev.me:
  - dns/domains/f4dev.me.js

domain/qubatura.art:
  - dns/domains/qubatura.art.js

domain/qubatura.com.pl:
  - dns/domains/qubatura.com.pl.js

domain/designcoach.pl:
  - dns/domains/designcoach.pl