# Base labels
DNS:
  - dns/**

repo:
  - .github/**
  - ./*

# Specific domains
domain/robroyart.xyz:
  - dns/domains/robroyart.xyz.js

domain/f4dev.me:
  - dns/domains/f4dev.me.js

domain/qubatura.art:
  - dns/domains/qubatura.art.js

domain/qubatura.com.pl:
  - dns/domains/qubatura.com.pl.js

domain/designcoach.pl:
  - dns/domains/designcoach.pl.js

domain/akademiaurzadzania.pl:
  - dns/domains/akademiaurzadzania.pl.js

domain/homecoach.pl:
  - dns/domains/homecoach.pl.js

domain/wnetrzabardzoosobiste.pl:
  - dns/domains/wnetrzabardzoosobiste.pl.js

domain/eduquality.eu:
  - dns/domains/eduquality.eu.js

# Domain groups/families
group/qubatura_company:
  - dns/domains/robroyart.xyz.js
  - dns/domains/f4dev.me.js
  - dns/domains/qubatura.art.js
  - dns/domains/qubatura.com.pl.js
  - dns/domains/designcoach.pl.js
  - dns/domains/akademiaurzadzania.pl.js
  - dns/domain/homecoach.pl.js
  - dns/domain/wnetrzabardzoosobiste.pl.js

group/designcoach:
  - dns/domains/designcoach.pl.js
  - dns/domains/akademiaurzadzania.pl.js
  - dns/domains/homecoach.pl.js
  - dns/domains/wnetrzabardzoosobiste.pl.js
