name: Deploy DNS zones

on:
  push:
    branches:
      - master

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    container:
      image: stackexchange/dnscontrol
    steps:
      - uses: actions/checkout@v2

      - name: Deploy DNS config
        uses: wblondel/dnscontrol-action@v3.15.0
        with:
          args: push

          config_file: 'dns/dnsconfig.js'
          creds_file: 'dns/creds.json'
        env:
          CLOUDFLARE_APITOKEN: ${{ secrets.CLOUDFLARE_APITOKEN }}
          OVH_APPSECRET: ${{ secrets.OVH_APPSECRET }}
          OVH_CONSUMERKEY: ${{ secrets.OVH_CONSUMERKEY }}
