name: Preview DNS changes

on: pull_request

# based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate DNS changes
        id: dnscontrol_preview
        uses: wblondel/dnscontrol-action@v3.15.0
        with:
          args: preview

          config_file: 'dns/dnsconfig.js'
          creds_file: 'dns/creds.json'
        env:
          CLOUDFLARE_APITOKEN: ${{ secrets.CLOUDFLARE_APITOKEN }}
          OVH_APPSECRET: ${{ secrets.OVH_APPSECRET }}
          OVH_CONSUMERKEY: ${{ secrets.OVH_CONSUMERKEY }}

      - name: Add comment to the pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              \`\`\`
              ${{ steps.dnscontrol_preview.outputs.preview_comment }}
              \`\`\`
              `
            })
