name: Preview DNS changes

on: pull_request

# based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate DNS changes
        id: dnscontrol_preview
        uses: koenrh/dnscontrol-action@v3
        with:
          config_file: dns/dnsconfig.js
          creds_file: dns/creds.json
        env:
          CLOUDFLARE_APITOKEN: ${{ secrets.CLOUDFLARE_APITOKEN }}
          OVH_APPSECRET: ${{ secrets.OVH_APPSECRET }}
          OVH_CONSUMERKEY: ${{ secrets.OVH_CONSUMERKEY }}

      - name: Add comment to the pull request
        uses: unsplash/comment-on-pr@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          check_for_duplicate_msg: true
